### PR TITLE
chore: add definition of PubId module, fixes #11

### LINKED ISSUE #11: NameError: uninitialized constant Pubid
```ruby
> require "pubid-core"
NameError: uninitialized constant Pubid
from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.8.0/lib/pubid-core.rb:3:in `<top (required)>'
```

blocks this https://github.com/relaton/relaton-bsi/issues/24, this https://github.com/relaton/relaton-nist/issues/63, and this https://github.com/relaton/relaton-jis/issues/2

### PR DESCRIPTION
**Pull request by ronaldtse**
Fixes #11.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@andrew2net can you please try if this fixes #11? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse no errors with this PR

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by ronaldtse** [comment]
@mico can you please help release pubid-core for this? Thanks.

**Pull request merged**
